const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Tween,
		C3.Behaviors.Pin,
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.skymen_mask,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.time,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.skymen_mask.Cnds.CompareInstanceVar,
		C3.Plugins.skymen_mask.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{arkaplan: 0},
	{masa: 0},
	{groupID: 0},
	{objectGroupID: 0},
	{posX: 0},
	{posY: 0},
	{DragDrop: 0},
	{Tween: 0},
	{balon: 0},
	{isFillKarisim: 0},
	{isFillParca: 0},
	{metalNo: 0},
	{siviNo: 0},
	{beherust: 0},
	{beheralt: 0},
	{isActive: 0},
	{isSelected: 0},
	{isStart: 0},
	{touchStartX: 0},
	{touchStartY: 0},
	{kavanoz: 0},
	{metalKap: 0},
	{isFill: 0},
	{spatul: 0},
	{karisim: 0},
	{gas: 0},
	{Pin: 0},
	{magnezyumParca: 0},
	{aliminyumParca: 0},
	{karbonatBtn: 0},
	{tursuBtn: 0},
	{magnezyumBtn: 0},
	{alüminyumBtn: 0},
	{leftOutX: 0},
	{leftInX: 0},
	{rightOutX: 0},
	{RightInX: 0},
	{elementBar: 0},
	{rightInX: 0},
	{cozeltiBar: 0},
	{ObjectGroup1: 0},
	{ObjectGroup2: 0},
	{Touch: 0},
	{Browser: 0},
	{gasMaskRightAlt: 0},
	{gasMaskRightUst: 0},
	{refreshBtn: 0},
	{audioBtn: 0},
	{shareBtn: 0},
	{fullScreenBtn: 0},
	{Audio: 0},
	{loaderEmpty: 0},
	{loaderFill: 0},
	{loaderLogo: 0},
	{Sprite2: 0},
	{outlineObjects: 0},
	{tintObjects: 0},
	{currentGroup1Index: 0},
	{currentGroup2Index: 0},
	{tintOpacity: 0},
	{isBlinkGroup2: 0},
	{isBlinkGroup1: 0},
	{isBlinkTint: 0},
	{soundControl: 0},
	{objectUID: 0},
	{isLoader: 0}
];

self.InstanceType = {
	arkaplan: class extends self.ISpriteInstance {},
	masa: class extends self.ISpriteInstance {},
	balon: class extends self.ISpriteInstance {},
	beherust: class extends self.ISpriteInstance {},
	beheralt: class extends self.ISpriteInstance {},
	kavanoz: class extends self.ISpriteInstance {},
	metalKap: class extends self.ISpriteInstance {},
	spatul: class extends self.ISpriteInstance {},
	karisim: class extends self.ISpriteInstance {},
	gas: class extends self.ISpriteInstance {},
	magnezyumParca: class extends self.ISpriteInstance {},
	aliminyumParca: class extends self.ISpriteInstance {},
	karbonatBtn: class extends self.ISpriteInstance {},
	tursuBtn: class extends self.ISpriteInstance {},
	magnezyumBtn: class extends self.ISpriteInstance {},
	alüminyumBtn: class extends self.ISpriteInstance {},
	elementBar: class extends self.ISpriteInstance {},
	cozeltiBar: class extends self.ISpriteInstance {},
	ObjectGroup1: class extends self.IArrayInstance {},
	ObjectGroup2: class extends self.IArrayInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	gasMaskRightAlt: class extends self.IWorldInstance {},
	gasMaskRightUst: class extends self.IWorldInstance {},
	refreshBtn: class extends self.ISpriteInstance {},
	audioBtn: class extends self.ISpriteInstance {},
	shareBtn: class extends self.ISpriteInstance {},
	fullScreenBtn: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	loaderEmpty: class extends self.ISpriteInstance {},
	loaderFill: class extends self.ISpriteInstance {},
	loaderLogo: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	outlineObjects: class extends self.ISpriteInstance {},
	tintObjects: class extends self.ISpriteInstance {}
}